name: CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ninja-build \
            libpq-dev

      - name: Configure CMake
        run: |
          cmake -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --parallel $(nproc)

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Configure CMake (MSVC)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Archive artifacts
        uses: actions/upload-artifact@v7
        with:
          name: odbtest-msvc_x64
          path: build/**/Release/*.exe
